### ISSUE TITLE
vscode open bash can't send signal correctly

### ISSUE THREAD

**Issue by zeromake** [msys2/Cygwin#57] opened 2021-10-14 06:33 UTC
msys2 install by `msys2-x86_64-20210725.exe` on `D:\msys2`.
on `vscode` settings.json
``` json
{
    "terminal.integrated.profiles.windows": {
        "bash": {
            "path": "D:\\msys2\\usr\\bin\\bash.exe",
            "args": ["--login"]
        }
    },
    "terminal.integrated.defaultProfile.windows": "bash",
}
```
`ctrl-c` can't send signal correctly.
![msys2](https://user-images.githubusercontent.com/8318747/137262686-36091df6-daf7-43d1-80da-3a6608503811.gif)

but change to git-windows it's normal(git 2.33.0.windows.2).
![git-windows](https://user-images.githubusercontent.com/8318747/137263812-8aee00a0-f4a6-4389-b1f7-4982ae007d39.gif)
 
use [msys2-runtime](https://packages.msys2.org/package/msys2-runtime?repo=msys&variant=x86_64) covered to git-windows will also appear.

**Comment by dscho** [comment] 2021-10-14 06:42
Have you tried updating MSYS2 via `pacman -Syu`? There was recent work to forward-port Ctrl-C handling from Git for Windows' fork of the MSYS2 runtime to MSYS2's version.

**Comment by zeromake** [comment] 2021-10-14 06:57
@dscho 

> Have you tried updating MSYS2 via `pacman -Syu`? There was recent work to forward-port Ctrl-C handling from Git for Windows' fork of the MSYS2 runtime to MSYS2's version.

now updating to `msys2-runtime-3.2.0-15` will also appear, can't send signal correctly.

**Comment by dscho** [comment] 2021-10-14 08:55
Sorry, I tried to reproduce, but it works for me as expected. Maybe you have some `TERM` or `LANG` or `LC_ALL` or `LC_CTYPE` settings, or a keyboard layout that interfere with the Ctrl+C functionality?

**Comment by zeromake** [comment] 2021-10-14 09:49
@dscho 
i find it is microsoft defender's Explpit Protection use `bash.exe` config, reset default it's normal

**Comment by dscho** [comment] 2021-10-14 09:51
@zeromake ah, that would make sense. So can we close this here ticket?

**Comment by zeromake** [comment] 2021-10-14 09:54
@dscho but i reboot pc, appeared again, later I will go home and find a clean windows10 to reproduce

**Comment by dscho** [comment] 2021-10-14 09:57
> 
> 
> @dscho but i reboot pc, appeared again, later I will go home and find a clean windows10 to reproduce

Can you add a Defender exclusion for MSYS2?

**Comment by zeromake** [comment] 2021-10-14 10:15
@dscho 
Defender antivirus scan exclusion for `D:\msys2`，`D:\program\git` and reboot pc, but nothing has changed.

**Comment by dscho** [comment] 2021-10-14 12:21
@zeromake sorry, I am out of ideas...

**Comment by zeromake** [comment] 2021-10-14 14:40
@dscho 
I home pc windows10 is reproduce, and found kill `bash.exe`, but bash not exit.

open a bash1
```cmd
PS D:\msys2> .\usr\bin\bash.exe --login
$ ps -a
      PID    PPID    PGID     WINPID   TTY         UID    STIME COMMAND
     1719       1    1719       2348  cons1     197608 22:35:17 /usr/bin/bash
     1750    1719    1750       7748  cons1     197608 22:35:34 /usr/bin/ps
```

open a bash2
```cmd
PS D:\msys2> .\usr\bin\bash.exe --login
$ ps -a
      PID    PPID    PGID     WINPID   TTY         UID    STIME COMMAND
     1751       1    1751      10436  cons0     197608 22:35:53 /usr/bin/bash
     1719       1    1719       2348  cons1     197608 22:35:17 /usr/bin/bash
     1781    1719    1781      10348  cons1     197608 22:35:57 /usr/bin/ps
```

kill `bash.exe` but not exit, need `kill -9`
```bash
$ kill 1751

$ ps -a
      PID    PPID    PGID     WINPID   TTY         UID    STIME COMMAND
     1751       1    1751      10436  cons0     197608 22:35:53 /usr/bin/bash
     1719       1    1719       2348  cons1     197608 22:35:17 /usr/bin/bash
     1783    1719    1783      11024  cons1     197608 22:37:25 /usr/bin/ps

$ kill -9 1751

$ ps -a
      PID    PPID    PGID     WINPID   TTY         UID    STIME COMMAND
     1784    1719    1784       4848  cons1     197608 22:39:29 /usr/bin/ps
     1719       1    1719       2348  cons1     197608 22:35:17 /usr/bin/bash
```

**Comment by zeromake** [comment] 2021-10-14 15:13
@dscho 
use git-windows `msys-2.0.dll` to msys2 replace, <Ctrl-C> is normal, but `kill` still can't exit.

git-windows `kill` test

open a bash1
```powershell
PS C:\Program Files\Git> .\bin\bash.exe --login
$ ps -a
      PID    PPID    PGID     WINPID   TTY         UID    STIME COMMAND
     1690       1    1690      10544  cons0     197608 23:09:27 /usr/bin/bash
     1714    1690    1714      10568  cons0     197608 23:10:12 /usr/bin/ps
```

open a bash2
```powershell
PS C:\Program Files\Git> .\bin\bash.exe --login
$ ps -a
      PID    PPID    PGID     WINPID   TTY         UID    STIME COMMAND
     1718       1    1718       9912  cons1     197608 23:10:57 /usr/bin/bash
     1742    1718    1742       6868  cons1     197608 23:11:01 /usr/bin/ps
     1690       1    1690      10544  cons0     197608 23:09:27 /usr/bin/bash
```

on bash1 kill bash2 is normal can exit.
```bash
$ kill 1718

$ ps -a
      PID    PPID    PGID     WINPID   TTY         UID    STIME COMMAND
     1750    1690    1750       7240  cons0     197608 23:12:23 /usr/bin/ps
     1690       1    1690      10544  cons0     197608 23:09:27 /usr/bin/bash
```

**Comment by zeromake** [comment] 2021-10-20 05:10
@dscho 
can you reproduce this operation kill bash

**Comment by dscho** [comment] 2021-10-20 11:18
@zeromake no, [I cannot reproduce](https://github.com/msys2/msys2-runtime/issues/57#issuecomment-943153917).

**Comment by zeromake** [comment] 2021-10-21 01:24
@dscho that I re-install system try.

**Comment by dscho** [comment] 2021-10-21 05:39
> @dscho that I re-install system try.

Sorry, I do not understand. Are you saying that you tried to reinstall your Windows?

**Comment by zeromake** [comment] 2021-10-21 06:23
@dscho 
yes I will open a virtual machine when I have time to install a new windows10 for testing.
The English above is all translated by Google，If I don’t understand well, I’m not embarrassed.

**Comment by zeromake** [comment] 2021-10-22 01:53
@dscho 
Use VirtualBox by 6.1.28 r14628 create vm windows10 by [microsoft vm](https://developer.microsoft.com/zh-cn/windows/downloads/virtual-machines/), vscode open bash `ctrl-c` not signal correctly and kill bash but not exit, all appeared.

**Closed as completed** 2022-06-20 02:57 UTC
